trigger:
- main

pool:
  name: NARESH

steps:
- script: java -version
  displayName: 'Check Java Version'

- script: mvn -version
  displayName: 'Check Maven Version'

- script: mvn clean test
  displayName: 'Run Selenium Tests'
