trigger:
- main  # or your branch name

pool:
  name: NARESH  # Your self-hosted agent pool name

steps:

- script: |
    java -version
    echo JAVA_HOME is $JAVA_HOME
  displayName: 'Check Java Version'

- script: |
    mvn -version
    echo MAVEN_HOME is $MAVEN_HOME
  displayName: 'Check Maven Version'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean test'
    mavenOptions: '-Xmx1024m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
  displayName: 'Run Maven Tests'
