trigger:
- main

pool:
  name: NARESH  # Make sure your self-hosted agent pool is correct

variables:
  JAVA_HOME: 'C:\Program Files\Java\jdk-21'
  MAVEN_HOME: 'C:\apache-maven-3.9.6'
  PATH: '$(JAVA_HOME)\bin;$(MAVEN_HOME)\bin;$(PATH)'

jobs:
- job: Build
  steps:
  - script: java -version
    displayName: 'Check Java Version'

  - script: mvn -version
    displayName: 'Check Maven Version'

  - script: mvn clean test
    displayName: 'Run Maven Tests'
