trigger:
- master  # or your branch name

pool:
  name: NARESH
  demands: []  # Removed tool demands like 'maven'

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'
    jdkArchitecture: 'x64'
    jdkSourceOption: 'PreInstalled'

- script: mvn clean test
  displayName: 'Run Maven Tests'
