trigger:
- master  # Change this to your branch name if different

pool:
  name: 'NARESH'  # Your self-hosted agent pool name

steps:
- script: |
    echo "✅ Verifying Java and Maven installation..."
    echo JAVA_HOME=%JAVA_HOME%
    echo MAVEN_HOME=%MAVEN_HOME%
    java -version
    mvn -version
  displayName: 'Verify Java & Maven Environment'

- script: |
    echo "🔧 Running Maven Clean Install..."
    mvn clean install
  displayName: 'Build Selenium Project'
