trigger:
- main  # Change as per your branch

pool:
  name: NARESH  # Your self-hosted agent pool name

steps:

- powershell: |
    Write-Host "Checking Java Version..."
    java -version
    Write-Host "JAVA_HOME: $env:JAVA_HOME"
  displayName: 'Show Java Version'

- powershell: |
    Write-Host "Checking Maven Version..."
    mvn -version
    Write-Host "MAVEN_HOME: $env:MAVEN_HOME"
  displayName: 'Show Maven Version'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean test'
    javaHomeOption: 'Path'
    jdkDirectory: '$(JAVA_HOME)'
    mavenOptions: '-Xmx1024m'
  displayName: 'Run Maven Tests'
