trigger:
  branches:
    include:
      - main  # or 'master' based on your repo

pool:
  vmImage: 'windows-latest'

steps:
- task: GitHubCheckout@1  # Optional: if using GitHub, or use built-in 'checkout'
  inputs:
    repository: self

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean test'
    options: '-X'
    mavenOptions: '-Xmx1024m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'  # or '17' based on your setup
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    testRunTitle: 'Selenium Test Results'
    mergeTestResults: true
