trigger:
- main

pool:
  name: NARESH

variables:
  JAVA_HOME: 'C:\Program Files\Java\jdk-21'
  MAVEN_HOME: 'C:\apache-maven-3.9.6'

jobs:
- job: Build
  steps:
  - script: |
      echo "JAVA Version:"
      java -version
    displayName: 'Check Java Version'
    env:
      PATH: '$(JAVA_HOME)\bin;$(PATH)'

  - script: |
      echo "Maven Version:"
      mvn -version
    displayName: 'Check Maven Version'
    env:
      PATH: '$(MAVEN_HOME)\bin;$(JAVA_HOME)\bin;$(PATH)'

  - script: mvn clean test
    displayName: 'Run Maven Tests'
    env:
      PATH: '$(MAVEN_HOME)\bin;$(JAVA_HOME)\bin;$(PATH)'
